### ISSUE TITLE
Update Django to 2.2.x

### ISSUE THREAD

**Issue by staydecent** [inputlogic/django-api-starter#32]
One feature, which I now almost always end up using, is the autocomplete fields: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields

Makes searching for related objects much easier.

**Comment by weslord** [comment]
Looks like autocomplete fields have been available since 2.0, but upgrading is still a good idea.

**Comment by weslord** [comment]
Or maybe even 3.0?

Biggest possible source of issues with going to 3.0 is 3rd party libraries. `authtools`, for example, does not yet support Django 3.0... Although this is additional motivation to resolve #48.
