### ISSUE TITLE
Missing Pieces for Sending Firebase Push Notifications

### ISSUE THREAD

**Issue by eweisner1973** [inputlogic/django-api-starter#69]
Need pip install firebase-admin and add resulting dependencies to requirements.txt.

Need to generate new private key in Firebase Admin SDK and download to root of Django project. Then add to apps/firebase/libs.py. For example: 
cred = credentials.Certificate("app-5d9x5-firebase-adminsdk-8zaqr-e510f0c67f.json")

Note, not sure about storing these credentials in a json file with the project as far as security.

Lastly, in /apps/firebase/tasks.py->send_notification, add
from .libs import firebase_instance

**Comment by weslord** [comment]
Also might want to verify and update the example code in the README.md
